/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as ContactContactIdImport } from './routes/contact/$contactId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const ContactContactIdRoute = ContactContactIdImport.update({
  id: '/contact/$contactId',
  path: '/contact/$contactId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact/$contactId': {
      id: '/contact/$contactId'
      path: '/contact/$contactId'
      fullPath: '/contact/$contactId'
      preLoaderRoute: typeof ContactContactIdImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact/$contactId': typeof ContactContactIdRoute
  '/contact': typeof ContactIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact/$contactId': typeof ContactContactIdRoute
  '/contact': typeof ContactIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact/$contactId': typeof ContactContactIdRoute
  '/contact/': typeof ContactIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact/$contactId' | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact/$contactId' | '/contact'
  id: '__root__' | '/' | '/contact/$contactId' | '/contact/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactContactIdRoute: typeof ContactContactIdRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactContactIdRoute: ContactContactIdRoute,
  ContactIndexRoute: ContactIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact/$contactId",
        "/contact/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact/$contactId": {
      "filePath": "contact/$contactId.tsx"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
